### ISSUE TITLE
Urgent Help  The merchant does not accept this type of credit card.

### ISSUE THREAD

**Issue by AshishTiwariMEAN** [SammyK/codeigniter-authorize.net-arb-api#1]
Hi SammK,

We have got error from authorize payment getway.

The test transaction was not successful. (17) The merchant does not accept this type of credit card.

We want to allow all types of credit card. Can you please suggest me how we can configure .

Thanks,
Ashish T

**Comment by SammyK** [comment]
Hey @AshishTiwariMEAN! If you want to accept other kinds of credit cards you need to contact your merchant.
